{
    "client": "Thunder Client",
    "collectionName": "S.O.S.I.T.",
    "dateExported": "2023-10-06T21:21:23.811Z",
    "version": "1.1",
    "folders": [],
    "requests": [
        {
            "_id": "abc480cd-9d0d-455e-9cb2-21f5584f2c21",
            "colId": "570beff4-68d4-4ec2-837d-f6de4b33cc79",
            "containerId": "",
            "name": "Autenticar Usuario",
            "url": "http://localhost:3333/usuario/autenticar",
            "method": "POST",
            "sortNum": 40000,
            "created": "2023-10-06T19:15:26.486Z",
            "modified": "2023-10-06T21:20:18.127Z",
            "headers": [],
            "params": [],
            "body": {
                "type": "json",
                "raw": "{\n  \"data\": {\n    \"email\": \"empresa00@login.com\",\n    \"senha\": \"12345\"\n  }\n}",
                "form": []
            },
            "tests": []
        },
        {
            "_id": "c8103fc6-61d3-435b-b36d-9e95b9bc46db",
            "colId": "570beff4-68d4-4ec2-837d-f6de4b33cc79",
            "containerId": "",
            "name": "Criar Cliente",
            "url": "http://localhost:3333/usuario/cliente",
            "method": "POST",
            "sortNum": 60000,
            "created": "2023-10-06T19:24:26.349Z",
            "modified": "2023-10-06T20:36:21.584Z",
            "headers": [],
            "params": [],
            "body": {
                "type": "json",
                "raw": "{\n  \"data\": {\n    \"usuario\": {\n      \"nome\": \"Cliente 00\",\n      \"email\": \"cliente00@login.com\",\n      \"senha\": \"12345\"\n    },\n    \"contato\": {\n      \"email_contato\": \"cliente00@contato.com\",\n      \"telefone\": \"(00) 0.0000-0000\",\n      \"nome_contato\": \"Cliente 00\"\n    }\n  }\n}",
                "form": []
            },
            "tests": []
        },
        {
            "_id": "48ff0246-87f2-4179-9eb5-8e15ff724bda",
            "colId": "570beff4-68d4-4ec2-837d-f6de4b33cc79",
            "containerId": "",
            "name": "Criar Empresa",
            "url": "http://localhost:3333/usuario/empresa",
            "method": "POST",
            "sortNum": 70000,
            "created": "2023-10-06T19:29:08.269Z",
            "modified": "2023-10-06T21:19:48.407Z",
            "headers": [],
            "params": [],
            "body": {
                "type": "json",
                "raw": "{\n  \"data\": {\n    \"empresa\": {\n      \"nome\": \"Empresa 00\",\n      \"email\": \"empresa00@login.com\",\n      \"senha\": \"12345\"\n    },\n    \"contato\": {\n      \"email_contato\": \"empresa00@contato.com\",\n      \"telefone\": \"(00) 0.0000-0000\",\n      \"nome_contato\": \"Empresa 01\"\n    },\n    \"endereco\": {\n      \"cep\": \"00000-000\",\n      \"rua\": \"Rua\",\n      \"num\": \"00\",\n      \"cidade\": \"Cidade\",\n      \"estado\": \"Estado\"\n    },\n    \"informacoes_empresa\": {\n      \"cnpj\": \"00.000.000/0001-00\",\n      \"descricao\": \"Descrição\",\n      \"link_site\": \"https://www.google.com.br/?hl=pt-BR\",\n      \"img_perfil\": \"\"\n    },\n    \"dados_bancarios\": {\n      \"banco\": \"Banco\",\n      \"agencia\": \"Agencia\",\n      \"digito\": \"Digito\",\n      \"tipo_conta\": \"Tipo da Conta\",\n      \"conta\": \"Conta\"\n    }\n  }\n}",
                "form": []
            },
            "tests": []
        },
        {
            "_id": "fbad6023-c0a7-4734-9d45-e13da5d167bf",
            "colId": "570beff4-68d4-4ec2-837d-f6de4b33cc79",
            "containerId": "",
            "name": "Deletar Usuario",
            "url": "http://localhost:3333/usuario/deleta",
            "method": "DELETE",
            "sortNum": 70000,
            "created": "2023-10-06T19:39:04.323Z",
            "modified": "2023-10-06T20:06:09.885Z",
            "headers": [],
            "params": [],
            "auth": {
                "type": "bearer",
                "bearer": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjksInRpcG8iOiJjbGllbnRlIiwiaWF0IjoxNjk2NjIyNzM1fQ.RjymIMjfiuw1hWAj0O9FJXIMWpNlK3mIczYV5vSkLPE"
            },
            "tests": []
        },
        {
            "_id": "223e6b4f-cb2b-4f08-806c-81a18c21063d",
            "colId": "570beff4-68d4-4ec2-837d-f6de4b33cc79",
            "containerId": "",
            "name": "Listar Por Token",
            "url": "http://localhost:3333/usuario/listar-meu-perfil",
            "method": "GET",
            "sortNum": 90000,
            "created": "2023-10-06T20:37:28.022Z",
            "modified": "2023-10-06T21:17:56.476Z",
            "headers": [],
            "params": [],
            "auth": {
                "type": "bearer",
                "bearer": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidGlwbyI6ImNsaWVudGUiLCJpYXQiOjE2OTY2MjQ1ODF9.o6plFG328OoBrzgS1XanjzuefOihB3XpRgQWeZg02C0"
            },
            "tests": []
        },
        {
            "_id": "5b8af70d-a124-4a15-b65c-f96472b29995",
            "colId": "570beff4-68d4-4ec2-837d-f6de4b33cc79",
            "containerId": "",
            "name": "Listar Todos Usuários",
            "url": "http://localhost:3333/usuario/listar-todos/empresa",
            "method": "GET",
            "sortNum": 100000,
            "created": "2023-10-06T21:18:24.290Z",
            "modified": "2023-10-06T21:18:57.831Z",
            "headers": [],
            "params": [],
            "auth": {
                "type": "bearer",
                "bearer": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidGlwbyI6ImNsaWVudGUiLCJpYXQiOjE2OTY2MjQ1ODF9.o6plFG328OoBrzgS1XanjzuefOihB3XpRgQWeZg02C0"
            },
            "tests": []
        }
    ]
}